export const morbilidades = [
    {codigo: "A09", name: "Otras enfermedades diarreicos aguadas"},
    {codigo: "A05.9", name: "Intoxicación Alimentaria"},
    {codigo: "B15.9", name: "Hepatitis viral Tipo A"},
    {codigo: "A08.0", name: "Enteritis por Rotavirus"},
    {codigo: "J00", name: "Resfrio Común"},
    {codigo: "J06.9", name: "2/ Infeccion Aguda de las Vías Respiratorias Superiores / IRAS"},
    {codigo: "J11", name: "ETI / Enfermedad Tipo Influenza"},
    {codigo: "J11.0", name: "IRAG / Infección Respiratoria Grave"},
    {codigo: "J18.9", name: "Neumonías y Bronconeumonías"},
    {codigo: "U07.1", name: "Infección Respiratoria Aguda por COVID-19"},
    {codigo: "A90", name: "Dengue sin signos de alarma"},
    {codigo: "A90.1", name: "Dengue con signos de alarma"},
    {codigo: "A91", name: "Dengue Grave"},
    {codigo: "A92.0", name: "Enfermedad por virus Chikungunya"},
    {codigo: "A92.8", name: "Zika"},
    {codigo: "E40", name: "Kwashiorkor"},
    {codigo: "E41", name: "Marasmo Nutricional"},
    {codigo: "E42", name: "Kwashiorkor Marasmático"},
    {codigo: "E43", name: "Desnutrición proteico calórica severa"},
    {codigo: "E44.0", name: "Desnutrición proteico calórica de grado moderado"},
    {codigo: "W54.9", name: "Mordedura o Ataque de Perro, en lugar no especificado"}
]